version: "1"
networks:
  gift.net:
    driver: bridge

services:
  php:
    image: canals/php:latest
    environment:
      - http_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
      - https_proxy=http://www-cache.iutnc.univ-lorraine.fr:3128
    ports:
      - "40000:80"
    volumes:
      - ./gift.appli/public:/var/www/html
      - ./shared/img:/var/www/html/
      - ./gift.appli/src:/var/www/src
    networks:
      - gift.net
    depends_on:
      - sql

  sql:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "60000:3306"
    networks:
      gift.net:
        aliases:
          - sql.db

  adminer:
    image: adminer
    ports:
      - "50000:8080"
    networks:
      - gift.net